spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_APP_DB:trip-manager}
      username: ${MONGO_APP_USER:tripmanager_app}
      password: ${MONGO_APP_PASSWORD:<CHANGE_ME_elm^5Ic5VM>}
      authentication-database: ${MONGO_APP_DB:trip-manager}
      auditing:
        enabled: true
  thymeleaf:
    enabled: false
    check-template-location: false

  mail:
    host: ${EMAIL_HOST:localhost}
    port: ${EMAIL_PORT:25}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_APP_USER:tripmanager_svc}
    password: ${RABBITMQ_APP_PASSWORD:<CHANGE_ME_!vNE*d1iPl>}
    virtual-host: ${RABBITMQ_APP_VHOST:/trip-manager}
    management:
      url: http://${RABBITMQ_MANAGEMENT_HOST:localhost}:${RABBITMQ_MANAGEMENT_PORT:15672}
      username: ${RABBITMQ_USER:tripmanager_admin}
      password: ${RABBITMQ_PASS:<CHANGE_ME_rjt5C*2pI@>}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 1000
          multiplier: 2.0

web:
  cors:
    max-age: 3600
    allowed-origins:
      - http://localhost:4200
    allowed-methods:
      - GET
      - POST
      - PATCH
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - Requestor-Type
      - Authorization
      - Content-Type
      - Accept
      - X-Init-Token

sec:
  app:
    jwtSecret: ${JWT_SECRET:}
    jwtExpirationMs: 2550000
    jwtCookieName: auth-token

app:
  rabbit:
    enabled: true
  activation:
    scheme: http
    domain: localhost
    path: /activate-account
    port: 4200

token:
  expiration:
    secret: ${TOKEN_SECRET:}
    account-activation: PT72H
  initialization:
    value: ${TOKEN_INIT}

rabbitmq:
  exchange:
    default: tm.direct.exchange
  queue:
    email: queue.email
  routing:
    email: routingKey.email
  dlq:
    name: dlq
